### ISSUE TITLE
Responsive table breaks sticky table headers

### ISSUE THREAD

**Issue by rdd512** [alex/nyt-2020-election-scraper#247]
The addition of `.responsive-table` div stops the fixed headers on scroll from working due to the generated css that adds `overflow-x: auto;`.

```css
.table-responsive {
    display: block;
    width: 100%;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
}
```
